name: Deploy to DevOrg1

on:
  push:
    branches:
      - recordUpdater

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Authenticate to Salesforce
        run: |
          sf login org:dev \
          --client-id ${{ secrets.SF_CLIENT_ID }} \
          --client-secret ${{ secrets.SF_CLIENT_SECRET }} \
          --username ${{ secrets.SF_USERNAME }} \
          --set-default-dev-hub \
          --set-default-username \
          --instance-url ${{ secrets.SF_LOGIN_URL }} \
          --refresh-token ${{ secrets.SF_REFRESH_TOKEN }}

      - name: Deploy RecordUpdater Package to DevOrg1
        run: sf project deploy start --manifest manifest/recordUpdaterPackage.xml --target-org DevOrg1