name: Deploy to DevOrg1

on:
  push:
    branches:
      - main   # or the branch you want to trigger the deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Salesforce CLI (modern sf CLI)
      - name: Install Salesforce CLI
        uses: salesforcecli/setup-sf@v2

      # Step 3: Authenticate to your DevOrg1 using JWT
      - name: Authenticate to DevOrg1
        run: sf auth:jwt:grant \
              --client-id ${{ secrets.SF_CLIENT_ID }} \
              --jwt-key-file assets/server.key \
              --username ${{ secrets.SF_USERNAME }} \
              --set-default-dev-hub

      # Step 4: Deploy your Shopify package
      - name: Deploy Shopify package to DevOrg1
        run: sf project deploy start \
              --manifest manifest/shopifyPackage.xml \
              -u DevOrg1 \
              --verbose