name: Promote Release to Main

on:
  push:
    branches:
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  promote-release:
    name: Test & Merge release → main
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

       Skip all Salesforce steps if no auth is configured
       - name: Install Salesforce CLI
         run: |
           npm install @salesforce/cli --global
           sf --version

       - name: Run Apex Tests
         run: |
           if [ -f test-manifest.txt ]; then
             TEST_CLASSES=$(grep -v '^\s*$' test-manifest.txt | paste -sd, -)
             echo "🎯 Running tests: $TEST_CLASSES"
             # Add your auth + test command here
           

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch branches
        run: |
          git fetch origin main
          git fetch origin release

      - name: Checkout main branch
        run: git checkout main

      - name: Merge release into main
        run: git merge origin/release --no-edit

      - name: Push changes to main
        run: git push origin main

      - name: Notify success
        if: success()
        run: echo "✅ Successfully merged 'release' into 'main'"
