name: Auto PR from Release to Main

on:
  push:
    branches:
      - release  # Trigger when release branch gets updated

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authenticate with GitHub CLI using the default token
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # Create PR from release to main
      - name: Merge release into main
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout main
          git pull origin main
          git merge origin/release --no-ff -m "Auto-merge release → main"
          git push origin main
