name: Promote Release to Main

on:
  push:
    branches:
      - release  # Trigger whenever something is pushed to 'release'

permissions:
  contents: write  # Needed for merging and pushing
  pull-requests: write

jobs:
  promote-release:
    name: Merge release → main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for merging full history

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch branches
        run: |
          git fetch origin main
          git fetch origin release

      - name: Checkout main branch
        run: git checkout main

      - name: Merge release into main
        run: |
          git merge origin/release --no-edit

      - name: Push changes to main
        run: git push origin main

      - name: Notify success
        run: echo "✅ Successfully merged 'release' into 'main'"
